$schema: "http://json-schema.org/draft-04/schema#"

id: "project"
title: project
type: object
category: Administrative
program: '*'
project: '*'
description: >
  description of project.
additionalProperties: false
submittable: true
validators: null

systemProperties: 
  - id
  - state
  - released
  - releasable
  - intended_release_date

required: 
  - type
  - code
  - availability_type
  - dbgap_accession_number
  - programs
  - study_design
  - study_type
  - experimental_setting
  - organism
#  - provenance


uniqueKeys: 
  - [code]


links: 
  - name: programs
    backref: projects
    label: member_of
    target_type: program
    multiplicity: many_to_one
    required: true

properties:
  type:
    enum: [project]
  id:
    $ref: "_definitions.yaml#/UUID"
    systemAlias: node_id
    description: "UUID for the project."
  state:
    description: |
      The possible states a project can be in.  All but `open` are
      equivalent to some type of locked state.
    default: open
    enum:
        # open: the only state users can perform 'upload' actions
        # possible actions in `open`:
        #   - upload (no state change)
        #   - review -> review
        #   - release (project.released -> true)
        - open

        # locked: admin has locked project for review
        # possible actions in `locked`:
        #   - open -> open
        #   - submit -> submitted
        #   - release (project.released -> true)
        - review

        # submitted: An admin has submitted project, it is locked against
        #            upload.
        # possible actions in `submitted`:
        #   - process -> processing
        #   - release (project.released -> true)
        - submitted

        # processing: The system is processing data in the project and
        #             is locked against upload and submission
        #   - (system transition to open)
        #   - release (project.released -> true)
        - processing


        # closed: The closed state is introduced to replace the
        #         ``legacy`` state and means that no further action
        #         can be taken on the project
        #   - (system transition to open)
        #   - release (project.released -> true)
        - closed

        # DEPRECATED(2016-03-01): synonymous with closed. included for
        #                         backwards compatibility
        - legacy
  code:
    type: string
    description: "Unique identifier for the project, studyID"
  availability_type:
    description: "Is the project open or restricted?"
    enum:
      - Open
      - Restricted
  programs:
    $ref: "_definitions.yaml#/to_one"
    description: >
      Indicates that the project is logically part of the indicated project.
  study_design:
    enum:
      - dose response design
      - case control design
      - cross sectional design
      - genetic modification design
      - sex design
      - time series design
      - Not applicable
      - Missing
      - Not collected
      - Not provided
      - Restricted access
    description: "A plan specification comprised of protocols (which may specify how
      and what kinds of data will be gathered) that are executed as part of an investigation
      and is realized during a study design execution."
  study_type: 
    enum:
      - Not applicable
      - Missing
      - Not collected
      - Not provided
      - Restricted access
      - Teratology
      - Short term
      - Long term
      - Bacterial mutagenicity
      - Drosophila germ cell mutagenicity
      - In vitro micronucleus
      - In vivo alkaline comet assay
      - Mammalian cell cytogenetics
      - Mammalian cell mutagenicity
      - Micronucleus
      - Rodent cytogenetics
      - ADME
      - Immunotoxicology
      - Nematode
      - RACB
      - Tox21 - Phase II
      - Toxicogenomics
      - Toxicokinetics
      - Zebrafish
    description: "A categorical value specification that specifies the type of study
      from a list of study types"
  experimental_setting:
    enum:
      - Not applicable
      - Missing
      - Not collected
      - Not provided
      - Restricted access
      - in vivo
      - ex vivo
    description: ""
  organism:
    enum:
      - Not applicable
      - Missing
      - Not collected
      - Not provided
      - Restricted access
      - Homo sapiens
      - Mus musculus
      - Rattus norvegicus
      - Drosophila melanogaster
      - Danio rerio
      - Xenopus laevis
    description: ""
  provenance: 
    type: string
    description: "template version"
  dbgap_accession_number:
    type: string
    description: "The dbgap accession number provided for the project."

